### ISSUE TITLE
Allow setting TERM environment variable

### ISSUE THREAD

**Issue by lukebakken** [lxde/qterminal#100]
https://github.com/qterminal/qterminal/blob/master/src/main.cpp#L105

In order to be able to use the "Solarized Dark" color scheme in QTerminal and in `vim`, I have to use the following `TERM` value:

```
xterm-256color
```

The default of `xterm` results in incorrect colors:

![vim-with-xterm-env-value](https://cloud.githubusercontent.com/assets/514926/5193869/a3494a90-74ba-11e4-8211-ab8d227a8e23.png)

It would be great to allow a user to set this either via the command line, or via a profile. Right now I'm using the following workaround in my `.bashrc`:

``` bash
ppid_cmdline="$(< /proc/$PPID/cmdline)"
if [[ $ppid_cmdline == *qterminal* ]]
then
  export TERM=xterm-256color
fi
```

**Comment by jleclanche** [comment]
Do other terminal emulators allow setting this?

**Comment by lukebakken** [comment]
Yes, most allow it. For instance, I have attached a screenshot of `mintty` on Windows.

![mintty-term](https://cloud.githubusercontent.com/assets/514926/8137026/38e90c62-10f5-11e5-93f9-90e24e05c5cb.png)

I have had to set `TERM` within `konsole`, in this manner.

https://blog.cryptomilk.org/2006/08/09/konsole-256color/

**Comment by hotvic** [comment]
Bump, any news about this ?

**Comment by jleclanche** [comment]
I'll approve it but this needs a PR. If someone's willing to work on it please ping this issue.

**Comment by LeonardKoenig** [comment]
Isn't qterminal based on Konsole? Konsole does have this feature afaik

**Comment by jleclanche** [comment]
qtermwidget is based on an early fork of konsole's terminal widget.

**Comment by tidux** [comment]
Any progress on this?

**Comment by vktec** [comment]
If anyone wants a oneliner version of the workaround provided by @lukebakken, here you go:

```bash
[[ $(</proc/$PPID/cmdline) == *qterminal* ]] && export TERM="xterm-256color"
```

**Comment by leesah** [comment]
How about just use `xterm-256color` as default, like how gnome-terminal does?

**Comment by Trucido** [comment]
the above workarounds still don't solve complex PS1 prompts, I still get a plain no-color prompt and also a bash warning  
``bash: warning: command substitution: ignored null byte in input``  
I confirmed that it did set xterm-256color however, but the only way to get my colored ps1 in qterminal is to source /etc/profile  though I tried adding a line in both ~/.bashrc and ~/.profile to source /etc/profile but neither fixed the qterminal issue.
(this was tested on openSUSE Tumbleweed 20171125 with qterminal 0.8.0) 
I think it's safe to assume 256color support and hardcode it for now, or add an option like Konsole has to set the term environment.

**Comment by vktec** [comment]
@Trucido Sounds like an issue with your prompt. Mind sticking your bashrc online somewhere so I can have a look?

**Comment by Trucido** [comment]
@vktec I'm using a modified version of the below paste in my global bashrc (but even unmodified it only works if TERM=xterm-256color is set and profile is sourced. I also tested pasting the unmodified version into qterminal )  
  
Any terms that don't explicitly set xterm-256color (including TERM=linux on my consoles) have a plain black&white PS1 prompt unless it's a basic prompt like:
```PS1='\[\e[00;32m\]\u\[\e[00m\]@\[\e[00;31m\]\h\[\e[00m\]:\[\e[00;36m\]\w\[\e[00m\]$ ' ```
  
I think most distros just assume 256color, either that or openSUSE's profile system is broken or they are conservative to accommodate serial consoles and other terms. Also, not sure if it matters but SUSE's /etc/profile sources ~/.bashrc (and presumably /etc/bash.bashrc before that) though their rc scripts are quite a nightmare to decipher. I might try and do some more advanced shell detection and maybe try and integrate this into /etc/profile.d to see if it works there  
  
either way, I still think qterminal should have an option to set term environment  
    
```
# Source for git information in prompt
if [ "${HIDE_GIT_PS1}" != "1" -a -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
  source /usr/share/git-core/contrib/completion/git-prompt.sh
  GIT_PS1_SHOWDIRTYSTATE=1
  GIT_PS1_SHOWSTASHSTATE=1
  GIT_PS1_SHOWUNTRACKEDFILES=1
#  GIT_PS1_SHOWUPSTREAM="verbose legacy git"
  GIT_PS1_DESCRIBE_STYLE=default
#  GIT_PS1_SHOWCOLORHINTS=1
else
  __git_ps1()
  {
    : # Git is not installed so stub out function
  }
fi

#Turn off annoying blinking if interactive
[ $TERM != "xterm" ] && setterm --blength 0 2>/dev/null

# Set terminal colours
BASE03=$(tput setaf 234)
BASE02=$(tput setaf 235)
BASE01=$(tput setaf 240)
BASE00=$(tput setaf 241)
BASE0=$(tput setaf 244)
BASE1=$(tput setaf 245)
BASE2=$(tput setaf 254)
BASE3=$(tput setaf 230)
YELLOW=$(tput setaf 136)
ORANGE=$(tput setaf 166)
RED=$(tput setaf 160)
MAGENTA=$(tput setaf 125)
VIOLET=$(tput setaf 61)
BLUE=$(tput setaf 33)
CYAN=$(tput setaf 37)
GREEN=$(tput setaf 64)
BOLD=$(tput bold)
RESET=$(tput sgr0)

# If we're root, then let's see red
if [ ${EUID} -eq 0 ] ; then
  USER_COLOUR="${RED}"
else
  USER_COLOUR="${GREEN}"
fi

# Check if we're local or remote or root
if [[ -n "${SSH_CLIENT}" || -n "${SSH_TTY}" || ${EUID} -eq 0 ]] ; then
  # Prompt with hostname
  export PS1="\[${RESET}\][\[${BASE0}\]\A\[${RESET}\] \[${USER_COLOUR}\]\u@\h \[${CYAN}\]\w\[${YELLOW}\]\$(__git_ps1 \" (%s)\")\[${RESET}\]]\\$\[${RESET}\] "
else
  # Just prompt
  export PS1="\[${RESET}\][\[${BASE0}\]\A\[${RESET}\] \[${USER_COLOUR}\]\u \[${CYAN}\]\w\[${YELLOW}\]\$(__git_ps1 \" (%s)\")\[${RESET}\]]\\$\[${RESET}\] "
fi
```

**Comment by emk2203** [comment]
@Trucido @vktec For newer bash versions (4.4 and above), the one-liner should be 
    `[[ $(</proc/$PPID/cmdline tr -d \\0) == *qterminal* ]] && export TERM="xterm-256color"`
to suppress the null byte warning.

For the issue in question, setting the TERM value by default to xterm-256colors would be better. `gnome-terminal` does it without obvious negative consequences, and the feature itself is beneficial. I use it for `mc` midnight commander over SSH a lot.

**Comment by yan12125** [comment]
Related: https://github.com/lxde/qtermwidget/issues/12

Agree that TERM=xterm-256color should be the default

**Comment by yan12125** [comment]
I created https://github.com/lxde/qterminal/pull/401. UI design feedbacks are welcomed.
