### ISSUE TITLE
Setting a larger font size doesn't do anything when openin new tabs

### ISSUE THREAD

**Issue by jleclanche** [lxde/qterminal#125]
Tabs are still opened with a smaller font size than usual.

**Comment by worblehat** [comment]
I can reproduce this, but only when I set a font size of 20 or above. For font sizes < 20 everything is fine. If the font size is >= 20 new tabs will have a smaller (the default?) font size. This problem persists even after restarting QTerminal.

**Comment by pmattern** [comment]
There seems to be a variant of the problem:
If several windows are opened changes made from the one opened last will only apply to that window, not to the other ones opened before. This does not seem to rely on distinct font sizes.

**Comment by f2404** [comment]
> If several windows are opened changes regarding the font made from the one opened last will only apply to that window, not to the other ones opened before. Finding doesn't seem to be limited to distinct font sizes.

Correct, and is this a bug? I'd rather see this as a feature thanks to which I can have different font settings for different windows.
