### ISSUE TITLE
Unsetting tab names

### ISSUE THREAD

**Issue by fturco** [lxde/qterminal#140]
It seems it is not currently possible to unset the name of a tab in QTerminal after having choosen one. In fact it may happen that you choose a tab name, work for a while, and then the name doesn't reflect the ongoing activity anymore, but you are not creative enough to choose another name, or have no time to do that.

**Comment by f2404** [comment]
Isn't this the same thing as renaming the tab?

**Comment by fturco** [comment]
Not really. In order to rename a tab you need to know which name to use. Unsetting a tab name doesn't require creativity at all. You can think of it as some sort of quick renaming to a default tab name scheme ("Shell No. X"). Yeah, you can type that manually, but a dedicated option would be better in my opinion.

**Comment by f2404** [comment]
OK, I see. Shouldn't be hard to implement.

**Comment by jleclanche** [comment]
This is really unnecessary functionality so I'm rejecting it. We'll clean up tab names though at some point...
