### ISSUE TITLE
Custom color schemes

### ISSUE THREAD

**Issue by fturco** [lxde/qterminal#141]
It would be great if QTerminal supported adding custom color schemes besides those shipped by default. For example I'd like to use [base16](https://github.com/chriskempson/base16) colors.

**Comment by jleclanche** [comment]
+1

**Comment by ke7ofi** [comment]
:+1:

**Comment by davidosomething** [comment]
:+1:

**Comment by ke7ofi** [comment]
:+1:

**Comment by hamburger1984** [comment]
:+1:

**Comment by jleclanche** [comment]
PRs welcome guys.

**Comment by rail-rain** [comment]
:+1:

**Comment by aabmass** [comment]
What folder should the user themes be loaded from in their home directory? 

It looks like qtermwidget already supports this if color schemes are installed in `/usr/local/share/qtermwidget5/color-schemes` or whatever gets passed to cmake for `-DCOLORSCHEMES_DIR=` when qtermwidget is compiled.

**Comment by f2404** [comment]
There's another location supported - `path_to_binary/color-schemes/`
I don't see much sense in this; I think it would make sense to look into let's say `~/.config/qtermwidget5/color-schemes/`, right?

**Comment by aabmass** [comment]
I think the reasoning for `path_to_binary/color-schemes/` is so that some Qt application embedding qtermwidget can include its color schemes like that. It looks like QTerminal already uses `.ini` `~/.config/qterminal.org/qterminal.ini`. Would it make sense to have a `color-schemes` folder next to that?

**Comment by aabmass** [comment]
Looks like Qt chooses. Check out main:
```C++
    QApplication::setOrganizationDomain("qterminal.org");
    // Warning: do not change settings format. It can screw bookmarks later.
    QSettings::setDefaultFormat(QSettings::IniFormat);
```

**Comment by f2404** [comment]
> I think the reasoning for path_to_binary/color-schemes/ is so that some Qt application embedding qtermwidget can include its color schemes like that. 

Ok, makes sense.

> It looks like QTerminal already uses .ini ~/.config/qterminal.org/qterminal.ini. Would it make sense to have a color-schemes folder next to that?

It could work for qterminal. For qtermwidget, we'd need another location.

**Comment by aabmass** [comment]
> It could work for qterminal. For qtermwidget, we'd need another location.
You lost me a little. Are you saying this feature belongs in qtermwidget and not qterminal here?

**Comment by f2404** [comment]
Sorry, I thought we were in the qtermwidget repo...
Yes, it actually belongs to qtermwidget (and your first comment is saying about that) - see https://github.com/lxde/qtermwidget/blob/master/lib/tools.cpp#L46

**Comment by aabmass** [comment]
Since the feature to load color schemes by file is already implemented in qtermwidget, I thought it would be easy enough to just use that here to load colorschemes from a directory specific to QTerminal? I'm wondering what others think.

**Comment by f2404** [comment]
In fact, this is not so straight-forward as current qtermwidget implementation only checks existence of the directories, not the actual presence of the schemes under them.
E.g., if it's given with a qterminal path `~/.config/qterminal.org/color-schemes/`, and the directory is empty, qtermwidget will not load any schemes, even those laying under `/usr/local/share/qtermwidget5/color-schemes`.

I think qtermwidget requires a serious revision in this area to support support multiple schemes locations. This change would allow adding custom paths from an app.

**Comment by f2404** [comment]
I've tried to implement my approach to this problem in the PR referenced above.

**Comment by aabmass** [comment]
I looked at your PR, this will definitely get this issue solved when it gets merged!

**Comment by f2404** [comment]
Thanks for the support @aabmass :)

**Comment by f2404** [comment]
No-one is willing to merge it so far...

**Comment by agaida** [comment]
@f2404 Don't be sad, i will check it tomorrow - had a little fight with systemd-cron in the past few days

**Comment by f2404** [comment]
OK, thanks @agaida :)

**Comment by agaida** [comment]
@f2404 compiles fine except the cmake part mentioned in the PR comments, now to something completely different - qterminal :D

**Comment by CrashyBang** [comment]
Hey guys sorry having a bit of trouble following this, so where can I put colorschemes to load them into qterminal? Also is there an example of a colorscheme format anywhere? Thanks in advance.

**Comment by yan12125** [comment]
> where can I put colorschemes to load them into qterminal

Put *.colorscheme files in ~/.config/qterminal.org/color-schemes

> is there an example of a colorscheme format anywhere

Pre-defined schemes files in /usr/share/qtermwidget5/color-schemes are good example :-)

**Comment by CrashyBang** [comment]
@yan12125 cheers for the fast response awesome will get into that now!

**Comment by noraj** [comment]
For the record, all Konsole themes works for Qterminal.

You can find Konsole themes [here](https://store.kde.org/browse/cat/462/) or install them via Konsole directly.

Then if you have both Konsole and Qterminal, just symbolic link Konsole color schemes into Qterminal ones.

```
cp --symbolic-link ~/.local/share/konsole/*.colorscheme ~/.config/qterminal.org/color-schemes
```

**Comment by l0rdh3lix** [comment]
> > where can I put colorschemes to load them into qterminal
> 
> Put *.colorscheme files in ~/.config/qterminal.org/color-schemes
> 
> > is there an example of a colorscheme format anywhere
> 
> Pre-defined schemes files in /usr/share/qtermwidget5/color-schemes are good example :-)

+1

Any idea what Color* and Color* Intense refer to? I'm trying to make a .colorscheme to recreate [this](https://old.reddit.com/r/Defcon/comments/cr5z55/defcon27_themed_terminal_colors_codes_in_comments/) but the descriptions don't exactly line up 
![image](https://user-images.githubusercontent.com/20142636/126871130-eada1d1f-5d6e-4cf9-818f-c5d0b5718efa.png)

**Comment by yan12125** [comment]
It's for "bold or increased intensity" colors [1]. You can check actual colors by a script from xterm: https://github.com/ThomasDickey/xterm-snapshots/blob/master/vttests/256colors2.pl. The second row in System colors are bold/intense ones.

[1] https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters
