### ISSUE TITLE
Add open link to context menu on links 

### ISSUE THREAD

**Issue by ianorlin** [lxde/qterminal#152]
In qterminal I would like the ability if I have a link like in irssi or other terminal based irc client man page to in the context menu be able to open the link with the context menu instead of having to hit control + click which is difficult for me. qterminal: An ability to copy the link could be nice as well. 

I am using version 
  Installed: 0.6.0-8
  Candidate: 0.6.0-8
  Version table:
 **\* 0.6.0-8 0
        500 http://ftp.uni-stuttgart.de/siduction/extra/ unstable/main amd64 Packages
        100 /var/lib/dpkg/status
on siduction. qterminal:
  Installed: 0.6.0-8
  Candidate: 0.6.0-8
  Version table:
 **\* 0.6.0-8 0
        500 http://ftp.uni-stuttgart.de/siduction/extra/ unstable/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by LightGuard** [comment]
CTRL+click is nice, but :+1: to having it on the right button context menu as well.

**Comment by yan12125** [comment]
Submitted pull request #276. Here's what I got:
![url-context-menu](https://cloud.githubusercontent.com/assets/1937689/19837312/84a8f676-9ef2-11e6-90c5-a5b0c3bebb1f.png)

**Comment by yan12125** [comment]
This is implemented now
