### ISSUE TITLE
QTerminal seems to have some serious memory leaks

### ISSUE THREAD

**Issue by PCMan** [lxde/qterminal#156]
I have a long running shell script which grabs some web data with a rate of 1 file every 3 seconds.
I ran it for 5 days in a qterminal tab with bash and it keeps printing the filename it downloads.
After 5 days, I found that the memory usage of qterminal process becomes roughly 3-4 GB.
I killed qterminal and the memory usage became lowered.
There seems to be some memory leaks in qterminal.

**Comment by pvanek** [comment]
question: how do you have set your Preferences / Behavior / History ? Unlimited?

**Comment by PCMan** [comment]
Limited: 1000.
Other settings should be the default values.
I did not remember changing anything other than the font.

**Comment by tsujan** [comment]
I left the drop-down qterminal running and used it many times for a full working day and yet couldn’t see any memory leak. However, I didn't use it to get web data.

**Comment by PeeJay** [comment]
I've just run into the same problem - long running script with much output. After 2 days 4 tabs were using 9GB. My history is also the default 1000.

**Comment by tsujan** [comment]
@PeeJay 
Konsole doesn't depend on KDE anymore. Could you use it instead of QTerminal and see if there's still a memory leak? I can't test because I don't do such heavy jobs.
