### ISSUE TITLE
dialog "Terminal settings": width of left pane should be variable

### ISSUE THREAD

**Issue by pmattern** [lxde/qterminal#190]
The width of left pane in dialog "Terminal settings" is static, as a consequence text may get cut besides plenty of space is available on the screen.
![qterminal_preferences-width-left-pane](https://cloud.githubusercontent.com/assets/9860801/11671128/4f10b636-9e06-11e5-9e05-f7776aefdd55.png)

So I think it would improve the UX if the width of left pane could get adjusted manually or if there was even a means to have it adjusted automatically to the text that's displayed.

**Comment by f2404** [comment]
In fact, the width is not static - it changes when resizing the entire window.
But I'm suggesting to increase the starting width - the Russian lines didn't fit into the old one as well.
