### ISSUE TITLE
Make tab active when right-clicking on it

### ISSUE THREAD

**Issue by f2404** [lxde/qterminal#198]
Now, as the context (right-click) menu actions are applied to the tab that the mouse was pointed over, we need to make that tab active when the menu is shown.
Looks like we want this behavior to be optional.

**Comment by pmattern** [comment]
Hm, are you sure about this one?

It can be very convenient to e. g. rename some tab while watching what's going on in another one. Also, as pointed out in #189, several other applications, among other Konsole, don't activate a tab upon opening its context menu either.

So IMO the behaviour introduced in 616c47b is just fine. If you should introduce ativating a tab by opening its context menu I'd really ask to make it an option and not something mandatory.

**Comment by f2404** [comment]
I've recalled the for now PR, thanks.
