### ISSUE TITLE
qterminal segfaults when collapsing vertical subterminals

### ISSUE THREAD

**Issue by agaida** [lxde/qterminal#212]
@palinek @pvanek @paulolieuthier
Please see full bug at: http://bugs.siduction.org/issues/1853
 backtrace and a video how to reproduce are attached. Source is  31d21b7

**Comment by palinek** [comment]
Me?
I'm neither using the qterminal nor did I ever change anything in its code base...

**Comment by agaida** [comment]
sorry @palinek

**Comment by f2404** [comment]
@agaida ?

**Comment by agaida** [comment]
GTM

**Comment by agaida** [comment]
Fixed with lxde/qterminal/67e2ba
