### ISSUE TITLE
Some fonts miss line spacing

### ISSUE THREAD

**Issue by Lanrik** [lxde/qterminal#226]
[screenshot](http://i.imgur.com/jcZHIku.jpg)

**Comment by f2404** [comment]
How did you achieve this?
What are your font settings?

**Comment by Lanrik** [comment]
Oh, this is only appear on 'Courier New' font. I dont know why it was by default.

**Comment by f2404** [comment]
Yep, it actually looks the same for me if using Courier New. (but I'm not using it for my terminals)
xfce4-terminal, however, is feeling fine with this font so looks like a qterminal (or qtermwidget) issue.

**Comment by f2404** [comment]
Could you maybe rename the issue to point to the font problem?

**Comment by pmattern** [comment]
This is a well-known problem in QTermWidget discussed in lxde/qtermwidget#46.
