### ISSUE TITLE
Pasting using hotkey does not always work

### ISSUE THREAD

**Issue by 0xR** [lxde/qterminal#227]
When I use the rightclick menu it does work. It also works when I run qterminal as root. 

When it doesn't work I only get `^V` character like so:
```
 user@machine  ~  ^V
```

I am running qterminal 0.6.0 with zsh on arch linux. With emulation set to default.

**Comment by f2404** [comment]
Looks like your Shift key is not working very well...
Also, I'm getting this result if using Left Ctrl + Lift Shift which are assigned to keyboard layout switch. This is why I'm using Right Ctrl and Right Shift for hotkeys.

**Comment by r-a-v-a-s** [comment]
File
:arrow_right: Preferences
:arrow_right: Shortcuts

Change "Paste Clipboard" to: Ctrl+V
It works fine for me.

**Comment by r-a-v-a-s** [comment]
Could this be because of https://github.com/lxde/qterminal/issues/220 ?

**Comment by 0xR** [comment]
Could be, I also have the menu bar hidden. Will investigate when I'm at my
laptop.

Op wo 25 mei 2016 00:36 schreef ravas <notifications@github.com>:

**Comment by 0xR** [comment]
If I display the menu bar the issue is resolved.

**Comment by 0xR** [comment]
Changing the hotkey to Ctrl+V does not work

**Comment by 0xR** [comment]
Duplicate of #220
