### ISSUE TITLE
incomplete pro file / building with Qt Creator

### ISSUE THREAD

**Issue by r-a-v-a-s** [lxde/qterminal#229]
I've been tweaking qterminal.pro in an attempt to build;
however, it complains about some static functions not being defined:

```
    static quint32 nativeKeycode(Qt::Key keycode);
    static quint32 nativeModifiers(Qt::KeyboardModifiers modifiers);

    static bool registerShortcut(quint32 nativeKey, quint32 nativeMods);
    static bool unregisterShortcut(quint32 nativeKey, quint32 nativeMods);
```

It seems like the lxde team doesn't use pro files and Qt Creator...
I don't understand that.

Regardless... how is this program building with undefined functions?

**Comment by r-a-v-a-s** [comment]
I see they are defined in the _win _mac _x11 files...
I'll keep this open until I have a working pro file.

**Comment by r-a-v-a-s** [comment]
Latest error:
`qxtglobalshortcut_x11.o: undefined reference to symbol 'XStringToKeysym'`
I see `#include <X11/Xlib.h>` in `qxtglobalshortcut_x11.cpp`

I tried `INCLUDEPATH += /usr/include/X11`
but that didn't work.

Does this require using `LIBS`?

**Comment by r-a-v-a-s** [comment]
@agaida Sigh... I just fixed it.

**Comment by r-a-v-a-s** [comment]
@agaida Can you please revert your commit?

**Comment by r-a-v-a-s** [comment]
It builds fine in Creator now...
I can test it on my iMac in a day or two.

**Comment by agaida** [comment]
done
