### ISSUE TITLE
Drop qterminal.pro

### ISSUE THREAD

**Issue by agaida** [lxde/qterminal#230]
one working and maintained build system should be enough and would solve #229 without much work

**Comment by r-a-v-a-s** [comment]
If you had a working .pro file I could already be working on something else... ;-]
If someone can help me fix it, then other Qt developers can more easily get started as contributors.

**Comment by agaida** [comment]
@r-a-v-a-s you miss a relative important point - the whole project use cmake, also qterminal and the widget do so. So one could consider the .pro-file al a forgetten leftover which brings no benefit for potential users and contributors.

**Comment by r-a-v-a-s** [comment]
I just found: http://doc.qt.io/qtcreator/creator-project-cmake.html

However: https://forums.opensuse.org/showthread.php/518010-how-can-I-install-usr-lib64-libEGL-so
