### ISSUE TITLE
Mouse pointer loses its shape after showing context menu

### ISSUE THREAD

**Issue by f2404** [lxde/qterminal#245]
Mouse pointer transforms from a vertical line into the usual mouse pointer (the arrow) when showing the context menu, and does not recover its shape after closing the menu. The shape gets restored after switching to another tab.
gtk/vte based terminals also transform the pointer into the arrow when showing the menu but restore the shape after closing it.

**Comment by yan12125** [comment]
This can't be reproduced with the latest qterminal & Qt 5.9.2

**Comment by f2404** [comment]
I'm not using qterminal anymore; feel free to close the issue if it's been fixed.

**Comment by yan12125** [comment]
Thanks for the response!
