### ISSUE TITLE
Can't tweak font setting

### ISSUE THREAD

**Issue by Adrianzo** [lxde/qterminal#246]
I don't know what happened. I can't switch back to any other font apart from FreeMono (which now I hate).

Worst thing: I don't know how to make a profile file to call and force a new font.

Worst worst thing: I don't know where the config files are to copy. That should be in the man page!

:-1: 

please help!

BTW. I like the work your doing. I will take this chance to say that I really appreciate it and thankful of it.

**Comment by agaida** [comment]
hmm - one could use strace qterminal to find the config file for qterminal
---
hmm, the second choice is to use: ${EDITOR} ~/.config/qterminal.org/qterminal.ini - and only a wild bet - it might help if a file in ${HOME} is owned by the user and the user have the needed rights to read and write this file.

**Comment by f2404** [comment]
@agaida, I agree that eventually font settings should become human-readable. I will try to look into this but I need to get an understanding how to support both variants of settings, and how to update configs with new setting.

**Comment by agaida** [comment]
@f2404, it would be nice to have, not that important, but nice :)

**Comment by felixsanz** [comment]
Any update? How can i manually change the font?

**Comment by yan12125** [comment]
@felixsanz None yet. Updates will be pasted to #218

**Comment by felixsanz** [comment]
@yan12125 But there is no way to change it right now? It is impossible to interpret that syntax?

**Comment by yan12125** [comment]
The data format spec can be found here: http://doc.qt.io/qt-5/datastreamformat.html. QFont and QString specs are relevant.

**Comment by agaida** [comment]
```
[General]
...
colorScheme=BreezeModified
emulation=linux
enabledBidiSupport=true
fontFamily=Bitstream Vera Sans Mono
fontSize=12
...
```
So what is the problem here? Solved long time ago - and the only "problem" with the font format befor was that the fact, that is was a bit hard to read for a mere human. Anyways - fonts should be set with the UI, i would leave the ini files up to upstream and distributions.
