### ISSUE TITLE
Blinking cursor

### ISSUE THREAD

**Issue by Hummer12007** [lxde/qterminal#259]
The cursor doesn't blink (and it can't be enabled) in qterminal, unlike xterm, rxvt, vte and friends.
This option would be a nice addition. Not sure whether it belongs here or in qtermwidget.

**Comment by yan12125** [comment]
For interested, please test https://github.com/lxde/qtermwidget/issues/132 and https://github.com/lxde/qterminal/pull/342, thanks!

**Comment by yan12125** [comment]
Fixed!

**Comment by agaida** [comment]
@yan12125 - only a short question - but how to set the cursor blinking in the UI? There are right now only the different shapes implemented or am i blind?

**Comment by yan12125** [comment]
@agaida: one have to insert an escape sequence manually - possibly in .bashrc/.zshrc/etc...
```
echo -e "\e[0 q"
```

**Comment by morfikov** [comment]
So is `echo -e -n "\e[0 q"` the only option to have the blinking cursor?

**Comment by yan12125** [comment]
Yep it's the standard way to change cursor shapes. Other codes can be found at https://github.com/lxqt/qtermwidget/pull/132#issue-131238513.
Also, feel free to submit patches that extend the View -> Keyboard Cursor Shape menu and include blinking options.

**Comment by yan12125** [comment]
> Also, feel free to submit patches that extend the View -> Keyboard Cursor Shape menu and include blinking options.

Ah, there is already a ticket at https://github.com/lxqt/qterminal/issues/343.
