### ISSUE TITLE
Some unicode characters doesn't show

### ISSUE THREAD

**Issue by cjnucette** [lxde/qterminal#277]
For example if you try in bash:
`echo -e "\u256D`
it should print ╭ but nothing gets printed.

**Comment by yan12125** [comment]
Need to port https://github.com/KDE/konsole/commit/1a61aaa5915b5c4a5b205e87d35c38562f932fe0 to qtermwidget

@cjnucette Are you developing TUI applications? Or any existing application uses these characters?

**Comment by cjnucette** [comment]
No, I'm using them in my prompt

![screenshot from 2016-10-31 16-00-19](https://cloud.githubusercontent.com/assets/2278326/19869595/5a2cb7b6-9f83-11e6-8c55-77a2d7512797.png)

`PS1="\[$lc\]┌─(\[$xc\]\!\[$lc\])─($sshtag\[$hc\]\h\[$lc\])─(\[$tc\]\w\$(git_color)\$(parse_git_branch)\[$lc\])\n└─\[$ac\]>\[$lc\]>\[\e[0m\] "`

**Comment by yan12125** [comment]
I've opened a pull request at https://github.com/lxde/qtermwidget/issues/98. Could you try it?

**Comment by cjnucette** [comment]
Sorry I wouldn't know how. I'm using Ubuntu and I installed qterminal using apt-get.

**Comment by yan12125** [comment]
As my pull request is not merged yet, you need to pull it and compile them from sources.
https://github.com/lxde/qtermwidget#compiling-sources
https://github.com/lxde/qterminal#compiling-sources

This is my testing result. I guess it's correct but I'm not sure, so I hope more people can test it.
![box-drawing-extra-chars](https://cloud.githubusercontent.com/assets/1937689/19889789/e8bbc636-a071-11e6-826c-98be91f67082.png)
