### ISSUE TITLE
Padding?

### ISSUE THREAD

**Issue by CrashyBang** [lxde/qterminal#285]
Hey I would really like to be able to add some padding to the window with `gnome-terminal` and similar it used to be achievable via `gtk.css` however this does not work with `qterminal` any suggestions?

**Comment by yan12125** [comment]
Could you paste a screenshot for what padding would look like?

**Comment by CrashyBang** [comment]
![onpaste 20161119-205748](https://cloud.githubusercontent.com/assets/2978850/20454082/e14d3c90-ae9a-11e6-80c0-1720cff56a84.png)

The space between the red box and the edge of the terminal window, if that makes sense?

**Comment by yan12125** [comment]
Thanks. I guess gtk.css can do much more than padding? Qt provides a similar mechanism called qss. However, some comments in QTerminal say that qss is not supported on Mac so don't use it. I don't know if it's still true or not as time goes by.

**Comment by CrashyBang** [comment]
I am not on a mac so might have a chance? Is there any material you can link that might indicate how to do this I had a google around but all I could find were references to the lzqt-runner and lxqt-panel?

**Comment by yan12125** [comment]
I don't know there's anyone using QTerminal on Mac, either. The conclusion is from git logs and code comments.

**Comment by CrashyBang** [comment]
Ah I see okay I will do some more looking into.

**Comment by yan12125** [comment]
Well, even qss are not going into qterminal, I guess it's still possible to implement padding only

**Comment by CrashyBang** [comment]
Hey @yan12125 what exactly do you mean?

**Comment by zoresvit** [comment]
So what would be the proper way to set padding for Terminal window only with `~/.config/qterminal.org/style.qss`?

I've tried

```
QWidget {
    padding: 10px;
}
```
But that affects all elements instead of just the terminal text area.

To illustrate, here's what the current default appearance is:

![Default QTerminal](https://i.imgur.com/ZUvTfr5.png)

This is what I'm trying to achieve (it's <s>photoshoped</s> GIMPed, note the padding around text area):

![Padded QTerminal](https://i.imgur.com/sKlcrSX.png)

PS: I figured this issue was to relevant to create a new one. Thanks!

**Comment by yan12125** [comment]
FYI:

* IIRC you can load the QSS just for QTerminal with a command line argument
* Margins are implemented in QTermWidget (https://github.com/lxqt/qtermwidget/pull/205). I believe remaining work is trivial to make it configurable from QTerminal preferences.

**Comment by aksh1618** [comment]
Can this be opened until the support is added?

**Comment by tsujan** [comment]
@aksh1618 The report is closed because configurable margins are implemeneted. See `Terminal settings → Appearance → Terminal margin` if you have an up-to-date installation.
