### ISSUE TITLE
Block Selection

### ISSUE THREAD

**Issue by mlopezgva** [lxde/qterminal#287]
As a terminal user, specially remote, were there's no simple way to share the transfer area, I use the selection on a regular basis to copy and paste, and since I use vim's windows and tmux panels, I usually end up selecting blocks with `Ctrl-Shift+Mouse` (gone-terminal and xfce4-terminal).

However qTerminal does not have this feature. Is there any hope to get it?

Thanks.

**Comment by yan12125** [comment]
Good idea!

**Comment by yan12125** [comment]
Aha I found it: hold down Ctrl+Alt when selecting

**Comment by mlopezgva** [comment]
I thought I tried this combination... BUT, I tried inside vim/tmux, so I needed to add the Shift key... and now it works. Fine, sorry. O:)

And thanks. :-)
