### ISSUE TITLE
launching neovim causes size of qterminal to increase and sets a minimumsize

### ISSUE THREAD

**Issue by surlykke** [lxde/qterminal#288]
I'm experiencing a weird problem - anybody else seing it? 
`Steps` to reproduce:
* Open qterminal
* launch nvim
  (the size of qterminal increased by 1 line)
* exit nvm
* try to decrease the size of the qterminal window with the mouse. It's not possible.
* every subsequent invocation of nvim increases the vertical size of qterminal by one line

The problem does not occur with vim. Nor does it occur in other terminal applications (tried xterm and terminology).

I'm not using lxqt, just openbox.

I've done a git bisect and found the behavior to be introduced by: 

d24725f4927b9d572b2bda190032b615fa639bf3: Removed minimum size (#265)

Reverting that commit fixes for me. I have no glimmer of an idea why this commit should cause this behavior.

I suppose the intent of d24725f4927b9d572b2bda190032b615fa639bf3 was to allow really small qterminal's, so as an alternative to reverting, one might apply this: 

```
diff --git a/src/forms/qterminal.ui b/src/forms/qterminal.ui
index c921f50..9814fcd 100644
--- a/src/forms/qterminal.ui
+++ b/src/forms/qterminal.ui
@@ -32,6 +32,12 @@
     </property>
     <item row="0" column="0">
      <widget class="TabWidget" name="consoleTabulator">
+      <property name="minimumSize">
+       <size>
+        <width>1</width>
+        <height>1</height>
+       </size>
+      </property>
       <property name="tabPosition">
        <enum>QTabWidget::South</enum>
       </property>
```

which also fixes.

**Comment by surlykke** [comment]
Sorry - forgot to mention: I'm using latest qterminal & qtermwidget from git.

**Comment by yan12125** [comment]
Reproducible

**Comment by hamburger1984** [comment]
Same here.

**Comment by agaida** [comment]
reproducible on debian/sid, latest q* from git

**Comment by yan12125** [comment]
The cause is that neovim sents a resize command to the terminal: https://github.com/neovim/neovim/blob/master/src/nvim/tui/tui.c#L422. The behavior can be simulated by:
```
echo -e '\e[8;30;20t'
```
After this command ```sizeHint()``` of the ```TerminalDisplay``` is changed. On the other hand, the TerminalDisplay has the size policy MinimumExpanding: https://github.com/lxde/qtermwidget/blob/master/lib/qtermwidget.cpp#L271, so the qterminal can't be shrunk to smaller than 30x20.

@surlykke I saw you wrote this line in https://github.com/lxde/qtermwidget/pull/7. I removed that line and seems the search bar is still working fine. Is there a reason for that line?

**Comment by surlykke** [comment]
Hmm. I'm afraid I have no recollection on why I put that there.
Are you saying that the bug I complained about was introduced by myself >4 years ago?
 Wow, that's kinda embarrassing :-(

**Comment by yan12125** [comment]
Not really. This bug is a combination of special behavior in neovim and the reaction of qterminal. I feel removing that line the best fix. Hope that won't bring other issues - https://github.com/lxde/qtermwidget/pull/123
