### ISSUE TITLE
Installing qterm{inal,widget} in custom locations

### ISSUE THREAD

**Issue by gauthma** [lxde/qterminal#295]
Hello,

First of all, the readme for this project states that QTermWidget is only a runtime dependency; I think this is not correct, because compiling qterminal without it will fail (cmake complains that it cannot find that dependency).

Now onto my problem per se: I wanted to install both pieces of software in a custom location, in my home folder (so I can tinker with them as time allows). I was able to do this for QTermWidget without changing anything in the code; but for qterminal, I had to change its CMakeLists.txt file. The diff is as follows:

~~~ cmake
@@ -161,6 +161,8 @@ else()
     add_definitions(-DTRANSLATIONS_DIR=\"${TRANSLATIONS_DIR}\")
 endif()
 
+link_directories( ${CMAKE_INSTALL_PREFIX}/lib )
+
 add_executable(${EXE_NAME} ${GUI_TYPE}
     ${QTERM_SRC}
     ${QTERM_UI}
~~~

That variable, CMAKE_INSTALL_PREFIX, contains the alternate location where qtermwidget had been installed (and where qterminal is also going). Without it, when `make`-ing qterminal, I always get the linker complaining that `-lqtermwidget5` could not be found.

If there is another way to accomplish my goal, without requiring source changes, I'd love to know about it! If there is not, then maybe my patch should be incorporated into the official file?

Anyway, thanks in advance (and thanks for the great work developing qterminal!)

**Comment by yan12125** [comment]
Hello, I opened a pull request at lxde/qtermwidget#118. That fixes building time issues for me, yet ```LD_LIBRARY_PATH``` is still necessary during runtime. Could you have a try?

> because compiling qterminal without it will fail

I guess just removing the word "Runtime" solves the potential confusion.

**Comment by yan12125** [comment]
FYI: Here's an updated README: https://github.com/lxde/qterminal/tree/update-readme

**Comment by yan12125** [comment]
Thanks to @luis-pereira, who proposed a much better solution than mine, this is already fixed in git-master. Note that ```$LD_LIBRARY_PATH``` is still necessary.
