### ISSUE TITLE
Allow disabling terminal size hint

### ISSUE THREAD

**Issue by michelboaventura** [lxde/qterminal#297]
Hi!

Is there a way to hide the size hint qterminal shows when it's being resized? I'm using it on i3 and found it to distract me a lot.

I've checked on source and couldn't find nothing. On qtermwidget I did found a way, but it seems to not be exported to qterminal.

Thanks!

**Comment by MSchuwalow** [comment]
I looked into it and do not see a way to do it without also patching the qtermwidget.
I uploaded a patched version to the AUR that you could try if you are on Archlinux.
https://aur.archlinux.org/packages/qterminal-nopopup-git/
