### ISSUE TITLE
Close tab shortcut : ctrl+w is already a bash known shortcut for clear line

### ISSUE THREAD

**Issue by bignaux** [lxde/qterminal#299]
... and crtl+d is a more common behaviour for terminal termination.

**Comment by yan12125** [comment]
Are you on Mac?

**Comment by bignaux** [comment]
No, on linux with lxqt desktop. Remove the shortcuts is fine, but counter-intuitive for new user of qterminal.

**Comment by yan12125** [comment]
On Linux default shortcuts use Ctrl+Shift+Foo ones: https://github.com/lxde/qterminal/blob/0e64b97/src/config.h#L77-L97. Not sure why you get Ctrl+Foo shortcuts...

**Comment by bignaux** [comment]
https://github.com/lxde/qterminal/commit/7e53b6cefb5926a18d9a2f25e76e319bfa5a5943
And i tested this terminal since its beggining, so i should have a qterminal.ini with old shortcuts. I confirm reset it, the default shortcuts are fine. Sorry for that.

**Comment by bignaux** [comment]
And btw, i should say this 0.7.1 is usable and i'll switch from my good xfce4-terminal.

**Comment by agaida** [comment]
ok - the old ini was very old - the first overhoul of keyboard commands that included Ctrl-W https://github.com/lxde/qterminal/commit/7e53b6cefb5926a18d9a2f25e76e319bfa5a5943
