### ISSUE TITLE
Duplicated menu entries after properties changed

### ISSUE THREAD

**Issue by yan12125** [lxde/qterminal#312]
This seems a bug caused by #256. After changing some properties (for example uses a smaller font size or vice versa), there are duplicate actions in the menu.
![duplicated_actions](https://cloud.githubusercontent.com/assets/1937689/24096569/29ad428a-0d9d-11e7-9f2c-4ab489bab930.png)

I guess ```rebuildActions``` does not clear previous actions completely. @pas2k Could you have a look?

**Comment by pas2k** [comment]
Well, that was a deeper rabbit hole than expected. Actually, almost no objects created with `new` in MainWindow were cleaned on Prefs updates. #313 fixes this.
