### ISSUE TITLE
Shortcut conflicts: termwidget scrolling & subterminal switching

### ISSUE THREAD

**Issue by yan12125** [lxde/qterminal#326]
Since lxde/qtermwidget@934107ae7de8dbabd7556c0b7d38b6f17b0e2187, Shift + Up/Down is used to scroll the termwidget. Shift + Up scrolls the term widget up by one line, and Shift + Down does the opposite. In application screens (tmux, vim, etc.), Shift + Up/Down/Left/Right are also used to send specific ASCII escape sequences.

In 5fa724c566b2b46b4295325346813abb0aa052e3, Shift + arrow keys are used to switch between subterminals. As this has a higher proirity, scrolling functions does not work anymore. Maybe we can have a different set of default shortcuts for switching subterminals? I don't use subterminals in daily work, maybe @pas2k has some ideas?

**Comment by pas2k** [comment]
I'm also not a fan of Shift+Directions to switch terminals, and only implemented those defaults to be similar to the previous layout.

Terminator has [sensible defaults](http://bazaar.launchpad.net/~gnome-terminator/terminator/gtk3/view/head:/terminatorlib/config.py), and uses Alt+Directions to switch terminals. In my configuration, I do the same and never found a place where it clashes with the TUI or CLI bindings.

Also, maybe we should add (again, based on Terminator):
- Shift+Alt+E for vsplit
- Shift+Alt+O for hsplit
- Shift+Alt+T for new tab

Terminator uses Shift+Ctrl, but I found Shift+Ctrl+E to be awkward to press in the heat of dev process.

**Comment by yan12125** [comment]
Use a similar set of shortcuts like Terminator sounds great. Do you know any other popular terminals with subterminals? Maybe we can add them all as we support multiple shortcuts for a single action :)

**Comment by pas2k** [comment]
There's VTE3.0-based [Tilix](https://github.com/gnunn1/tilix), and [iTerm2](https://www.iterm2.com/features.html).

Konsole has splits (but only for several views into a single pty), same as default OS X Terminal with Cmd+D.

I did my search for the alternative when I decided that Terminator was no longer maintainable (it was based on VTE 2.0 back then), but haven't found anything as promising as QTerminal for Linux, so there are only a few in existence.

**Comment by yan12125** [comment]
Thanks. For Tilix, it uses Ctrl+Tab and Ctrl+Shift+Tab, which are already used, too. For iTerm2, I guess having different shortcuts between macOS and Linux won't confuse users more.

However, when I changed all Shift + Directions to Alt + Directions, I find that those keys are not captured by QTerminal at first. I have to click on the Action menu once more to make them work. Did you encounter something similar? (I use Qt 5.9 beta 3, which might be the cause)

**Comment by pas2k** [comment]
No such issues for me -- double-checked it. Maybe, you have some Windows-like behavior where tapping Alt can focus the main menu of a window?

**Comment by yan12125** [comment]
Yes on my machine tapping Alt triggers the menu bar, and Alt + Up sends "\e[1;3A" to the terminal.

Maybe a Qt 5.9 bug. I'll check on another machine, which is still on 5.8.

**Comment by yan12125** [comment]
The problem is on 5.8, too. Anyway we can change shortcuts first and then fix the bug.

**Comment by pas2k** [comment]
Too bad I cannot repro the binding bug. If anyone has repro steps for a clean VM installation (preferably not Ubuntu, since apparently, it doesn't repro on it), please place it in a separate ticket. It's not the first time it comes up, btw.

**Comment by yan12125** [comment]
I opened #327 to change the default shortcuts and #328 for the aforementioned issue. It's subterminal-specific but a more generic problem.
