### ISSUE TITLE
How to use more fonts?

### ISSUE THREAD

**Issue by felixsanz** [lxde/qterminal#333]
I'm trying to compile my own version for testing purposes, messing with this:

```
    fontComboBox->setFontFilters(QFontComboBox::MonospacedFonts | QFontComboBox::NonScalableFonts | QFontComboBox::ScalableFonts);
```

But even modifying the project i can't get to see more fonts. Where is that small list coming from? I have more monospaced fonts that doesn't appear :/

**Comment by felixsanz** [comment]
Fixed! Apparently this line was filtering the fonts again: `if (QFontInfo(f).fixedPitch())`

Now i can finally use my Nerd Fonts on QTerminal n_n

**Comment by yan12125** [comment]
You got it! FYI: non-monospaced fonts are filtered out as it brings mysterious bugs. (ex: #292) Be prepared for something broken :)

**Comment by felixsanz** [comment]
@yan12125 Those fonts that i was trying to use are monospaced fonts. They just don't apparear on the list for whatever reason.

**Comment by yan12125** [comment]
Hi, could you point me where to download the "nerd fonts"? If Qt fails to identify monospace fonts, it's a good idea to allow all fonts in qterminal.

**Comment by pvanek** [comment]
I don't think so. To allow non-monospaced fonts can break the widget display. Qt must be fixed.

**Comment by felixsanz** [comment]
I only tried Nerd Fonts because that fill my needs. You can find them [here](https://github.com/ryanoasis/nerd-fonts).

Also, in arch AUR: [nerd-fonts-complete](https://aur.archlinux.org/packages/nerd-fonts-complete/).

Those font doesn't appear and they are monospaced.

Also, i think also some other monospaced fonts doesn't appear, but i didn't test that at at all (i had a lot of fonts before and i remember that the font list was small)

**Comment by agaida** [comment]
after having a short look at the issue list of nerd-fonds i would say: Not really our problem, they should fix their scripts and documentation and we could have a look again. Meanwhile i would tend to ignore these kind of issues and concentrate on fixing real problems like double with characters and such things.

**Comment by felixsanz** [comment]
They should fix their scripts?

Who is "They" ? And what scripts?

**Comment by yan12125** [comment]
I guess @agaida meant the ```font-patcher``` script at https://github.com/ryanoasis/nerd-fonts

**Comment by felixsanz** [comment]
That script is only intended if you want to patch custom fonts. What it does have to do with this?

They provide some monospaced fonts already patched, and those doesn't appear on the font list.

The script `font-patcher` is just an utility in case you want to patch another fonts yourself.

**Comment by haskellcamargo** [comment]
Any updates on this? I'm trying to use Nerd fonts here, but they also don't show up. :cry:

**Comment by agaida** [comment]
We will not break qterminal for that - they should fix their font - it is easy as can be - should be no problem if nerd fonts are created by nerds. (In maybe nicer words: nerd fonts should be modified to be really monospaced and also declared as monospaced - with fixed char length, thats all)

**Comment by mlopezgva** [comment]
I have also come monospaced fonts (like Iosevka Type and a few others) and not all of them are shown.

**Comment by rvz420** [comment]
I have also some monospaced fonts (like fira code) not showing up

**Comment by tsujan** [comment]
I've dealt with mono fonts in various Qt codes and can say this with certainty:

Only fonts that return `true` for `QFontInfo::fixedPitch()` are considers mono. Whether some of the above-mentioned fonts aren't really mono or the Qt method has a problem is a question for the font or Qt developers.

So, if you are really sure that those fonts are mono but `QFontInfo::fixedPitch()` returns `false` for them, you could open an issue at Qt bug tracker. But make sure to have a solid reason that your fonts are mono — saying this or that app shows them as mono isn't a good reason.

BTW, Fira, installed from AUR, (and mentioned in the previous comment) is mono and is shown by the combo.
