### ISSUE TITLE
Change the window title to show the path and user

### ISSUE THREAD

**Issue by brandon14** [lxde/qterminal#347]
Is there anyway to have the QTerminal show the current user and the current path in the window title?
I know there is the option ChangeWindowTitle but it's a boolean option and I'm not sure what exactly it changes.

##### Expected Behavior
Open a new QTerminal in the home directory. Expect to see the current user and current path information in the window title.

##### Current Behavior
Shows QTerminal with now path or user information.

##### Context
Sometimes I have multiple terminal windows open and its nice to be able to see the path in the terminal's window title.

##### System Information
* Distribution & Version: Linux Mint 18.2 Cinnamon
* Kernel: 4.10.0-28

**Comment by yan12125** [comment]
First check that you have get Settings -> Appearance -> Change window title based on current terminal checked. If you didn't see that option, upgrade your qterminal. If the title is still unchanged, you can add escape sequences in .bashrc/.zshrc/... For example in bash:
```Bash
PROMPT_COMMAND='echo -ne "\e]2;$USER:$(pwd)\a"'
```
And in zsh:
```Bash
function change_title { echo -ne "\e]2;$USER:$(pwd)\a" }
precmd_functions+=(change_title)
```
For other shells, please check their manuals; I don't know how to create auto commands for them.
