### ISSUE TITLE
Opening a new tab should execute shell if specified

### ISSUE THREAD

**Issue by tarqe39** [lxde/qterminal#354]
If the qterminal is started using other shell using "-e" switch, and then a new tab is opened, the new tab will use bash shell instead of shell specified by the switch.
I think this would be a nice improvement.

**Comment by koehn** [comment]
Curiously, I get no shell at all when I open qterminal under [this project](https://gitlab.koehn.com/bkoehn/novnc-desktop.git). It only works if I specify a shell using the `-e` argument.

**Comment by yan12125** [comment]
@koehn: sounds a different issue. qterminal checks for ```$SHELL``` by default. Did you set it?

**Comment by yan12125** [comment]
@tarqe39: thinking again, it appears not a bug. ```qterminal --help``` says:
```
  -e,  --execute <command>  Execute command instead of shell
```
```-e``` is used to specify another program that _runs once_, and new tabs still run the shell. If you want to use an alternative shell, override ```$SHELL``` instead.

**Comment by koehn** [comment]
It appears `SHELL` is set, and isn't working: 

```
$ echo $SHELL
/bin/bash

$ qterminal
TRANSLATIONS_DIR: Loading translation file "qterminal_C.qm" from dir /usr/share/qterminal/translations
load success: false
Properties constructor called
QDir::exists: Empty or null file name
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x10d94b0, name = "TermWidget_1") emulation: "linux"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
Session::run() - program to run not set.
Session::run() - arguments: ("")
CRASHED! result:  -1
TermWidgetImpl::propertiesChanged TermWidgetImpl(0x10d94b0, name = "TermWidget_1") emulation: "linux"
QObject::connect: No such slot TabWidget::renameSession()
QObject::connect:  (receiver name: 'consoleTabulator')
```

All I get is a blank window with no shell:
![image](https://user-images.githubusercontent.com/583888/31237326-25d5e708-a9e6-11e7-8822-e2f13b643936.png)

**Comment by yan12125** [comment]
Maybe an old bug - the following two debugging message has been removed a long time ago
```
Session::run() - program to run not set.
Session::run() - arguments: ("")
```
Could you try with version 0.7.1? Or better, if you're willing to spend some time, compile the latest git revision?

By the way, messages like "No such slot TabWidget::renameSession()" is an indicator that qterminal is compiled against a different version of qtermwidget than it really uses. That can bring anything evil, crashes, misbehaviors, etc. How did you install qterminal? If you compile qtermwidget and qterminal by yourself, recompile them. If you installed them from a compiled package, notify its maintainer.

**Comment by koehn** [comment]
I'll try your suggestions. I installed using [this Dockerfile](https://gitlab.koehn.com/bkoehn/novnc-desktop/blob/master/desktop/Dockerfile) which installs into Ubuntu 16.04 (Xenial). I can try using a newer version (e.g., 17.10) and see if that helps.

**Comment by koehn** [comment]
OK, I've upgraded to 0.7.1 as installed by Ubuntu 17.10. Here's what I get now (still no shell in the qterminal window):

```
$ echo $SHELL
/bin/bash

$ qterminal
QDir::exists: Empty or null file name

$ qterminal --version
0.7.1
```

**Comment by yan12125** [comment]
Hmm, could you run ```strace -f qterminal``` and paste the output?

**Comment by koehn** [comment]
Here's [the output](https://gitlab.koehn.com/uploads/-/system/personal_snippet/16/e47c7f07b7bb38e8cebfb0dae279801a/strace.out) of `strace -f qterminal`.

Thanks!

**Comment by koehn** [comment]
OK, I think I figured it out. Somehow the SHELL variable wasn't exported, so it wasn't available to the qterminal process. When I added `export SHELL` (or set the shell with `adduser`) it works fine.

**Comment by yan12125** [comment]
Thanks for testing it! This can be closed now.

**Comment by koehn** [comment]
I'd recommend adding a test of the $SHELL variable and, in its absence, putting out a warning message and running something like `/bin/sh` or other reasonable default.

**Comment by yan12125** [comment]
Apparently the code is not working as intended.
