### ISSUE TITLE
Not able to execute some shortcuts in VirtualBox VM

### ISSUE THREAD

**Issue by NonerKao** [lxde/qterminal#362]
Hi all,

Sorry if duplicated here.

I have a fresh LXQt desktop on Arch Linux, as a guest machine using VirtualBox,
and basically the only application I use is the terminal.

I changed several hot key combinations such as
* `Next/Previous Tab` to `Ctrl+PgDown`/`Ctrl+PgUp`
* `Next/Previous Subterminal` to `Ctrl+Shift+Right`/`Ctrl+Shift+Left`

However, those four seldom work (they still doesn't work after I reset to default),
While some function like the `Ctrl+Shift+T` combination for adding tabs is always functioning well.

I would like to know that is anyone else encounter this issue?

##### System Information
* Distribution : Arch Linux
* Kernel: 4.13
* Qt Version: 5.9.2
* libqtxdg Version: 1.0.0  
* qtermwidget Version: 0.7.1
* lxqt-build-tools Version: Not clear
* Package version: 0.7.1

The host is Windows 7, 
* Virtual Box: 5.1.28

Thanks for any help.

**Comment by yan12125** [comment]
> Next/Previous Tab to Ctrl+PgDown/Ctrl+PgUp

I use the same configuration and it works fine. I remember there are some changes related to PgUp and PgDown keys since 0.7.1.

> Next/Previous Subterminal

Likewise, subterminal shortcuts has changed a lot (https://github.com/lxde/qtermwidget/issues/103).

Could you build qterminal-git and qtermwidget-git from AUR and check whether there are still problems or not?

Another possibility is that VirtualBox doesn't handle special keys well. ```xev``` is a good tool to test it.

**Comment by NonerKao** [comment]
@yan12125 Thanks for the quick reply! A nice software indeed, but...
it seems that the AUR package of qterminal-qt is broken,
so it would take some time for me to report the status.

**Comment by NonerKao** [comment]
Specifically, the error I got was
```
....../src/qterminal/src/main.cpp:19:24: fatal error: QApplication: No such file or directory
 #include <QApplication>
                        ^
compilation terminated.
```
No matter using AUR or manual compilation.

**Comment by yan12125** [comment]
Manual compilation should work fine. Could you check whether /usr/include/qt/QtWidgets/QApplication is there or not?

AUR packages are indeed broken. I'll contact their maintainer.

**Comment by NonerKao** [comment]
@yan12125 It's there.

**Comment by yan12125** [comment]
OK I fixed both AUR packages.

Could you try again? If that still fails, please paste full logs.

**Comment by NonerKao** [comment]
Everything works fine now!
Thanks for all the help.

**Comment by yan12125** [comment]
Great! Let's close this.
