### ISSUE TITLE
Configurable default window size

### ISSUE THREAD

**Issue by leesah** [lxde/qterminal#372]
##### Expected Behavior

Default window size is configurable.

##### Current Behavior

Default window size is not configurable.

##### Steps to Reproduce (for bugs)

1. Right-click in the terminal, select `Preferences`.
2. In `Appearance` tab, configure `default window size` with a `height` and a `width` in integers. (Configuration not available now)
3. In `Behavior` tab, unckeck `Save Position when closing`.
4. Click `OK`.
5. Re-open QTerminal window.

##### Context

The current default window size is too narrow for me. And the `Save Position when closing` (no idea why `Position` is capitalized tho) won't help because I use the window snapping feature which will resize the terminal window to half of the screen size. So what I want is to be able to start QTerminal in a bigger size than the current default, and at the same time not to let it remember the size when closing.

##### System Information

* Distribution & Version: 0.6.0+20160104-1
```bash
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

$ apt show qterminal 
Package: qterminal
Version: 0.6.0+20160104-1
Priority: optional
Section: universe/x11
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: LXQt Packaging Team <pkg-lxqt-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 546 kB
Provides: x-terminal-emulator
Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.5.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libqt5x11extras5 (>= 5.1.0), libqtermwidget5-0 (>= 0.6.0+20150709), libstdc++6 (>= 5.2), libx11-6
Homepage: https://github.com/lxde/qterminal
Download-Size: 150 kB
APT-Manual-Installed: yes
APT-Sources: http://se.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: Lightweight Qt terminal emulator
 QTerminal is a lightwight terminal emulator based on QTermWidget.
 .
 Among other it features
   * Split terminals (horizontally and vertically).
   * Multiple tabs.
   * Customizable shortcuts.
   * Various color schemes.
```

* Kernel: 
* Qt Version: 
* libqtxdg Version: 
* qtermwidget Version:
* lxqt-build-tools Version:
* Package version:

**Comment by yan12125** [comment]
Thanks for the proposal. This is already discussed in #284 and there are some non-GUI approaches.
