### ISSUE TITLE
Can't find qmake

### ISSUE THREAD

**Issue by Mortal-Wombat-14** [lxde/qterminal#385]
I am trying to compile qterminal but i get the error message: line 13: /home/steamlink-sdk-master/external/qt-everywhere-opensource-src-5.9.1/build/host/bin/qmake: No such file or directory

I can go to the directory and find the file, but steamlink can't

Any help?

**Comment by yan12125** [comment]
You'll need to ask steamlink developers. BTW, it's recommended to use cmake instead of qmake. Check out https://github.com/lxde/qterminal/blob/master/README.md#compiling-sources.
