### ISSUE TITLE
Wrong $COLUMNS of terminal at start

### ISSUE THREAD

**Issue by unclechu** [lxde/qterminal#39]
When I run the terminal — my .bashrc fills first line like this:
username@hostname:~ ────────────────────────────────────────
But in qterminal I have some like this:
username@hostname:~ ───────────
───────────────────────────
──
At the start we have correct $COLUMNS value, but width terminal in the moment probably have not full size. And this happens only on first start, in new tab or split, or new line of command works fine.

**Comment by jleclanche** [comment]
Closing due to lack of feedback.
