### ISSUE TITLE
Add  Tango color scheme [feature_request]

### ISSUE THREAD

**Issue by selivan** [lxde/qterminal#391]
It would be nice to have Tango color scheme available, it's mild and nice to look at.

##### Expected Behavior
Add the following color scheme named "Tango":

```
#000000 black
#CC0000 red
#4E9A06 green
#C4A000 yellow
#3465A4 blue
#75507B magenta
#06989A aqua
#D3D7CF grey
#555753 light black
#EF2929 light red
#8AE234 light green
#FCE94F light yellow
#729FCF light blue
#AD7FA8 light magenta
#34E2E2 light aqua
#EEEEEC light grey
```

Got it from gnome-terminal settings:

![image](https://user-images.githubusercontent.com/1208989/35084720-6216f980-fc36-11e7-874e-c2c107c1cb7f.png)

##### Context

My favorite terminal color scheme, can't live without it :)

**Comment by yan12125** [comment]
FYI: you can add custom color schemes to ```$HOME/.config/qterminal.org/color-schemes```. Check https://github.com/lxde/qtermwidget/tree/master/lib/color-schemes for file formats.

**Comment by selivan** [comment]
@yan12125 Thanks! I could not find in qterminal sources where color themes are defined, so I created this ticket. Now when you pointed this out I created a PR to add Tango color scheme to qtermwidget: https://github.com/lxde/qtermwidget/pull/167

**Comment by yan12125** [comment]
Fixed :)
