### ISSUE TITLE
can i remove the "Size: XX x YY" announce every time i start or resize?

### ISSUE THREAD

**Issue by noformnocontent** [lxde/qterminal#405]
can i remove the "Size: XX x YY" announce every time i open or resize window?

##### Expected Behavior
dont announce the term size

##### Current Behavior
announce the term size on open and every resize

##### Steps to Reproduce (for bugs)
1. Open.
2. Resize.

##### Possible Solution
maybe if i uncheck the "Save position on exit" and "Save size on exit" in the settings, it should stop announcing the size?

##### Context
its really annoying on tiling window managers who resize windows by themselves

##### System Information
* Distribution & Version: Arch
* Window Manager: i3
* Package version: 0.8.0

**Comment by yan12125** [comment]
Already fixed in https://github.com/lxde/qterminal/commit/eb18afdd1285e9c3fe88d4d349fcf4babaea2a75
