### ISSUE TITLE
Tab names should be dynamic

### ISSUE THREAD

**Issue by GinoM** [lxde/qterminal#52]
Names on Tabs should be dynamic and reflect running application, or at least support some customization via variables

Example: 
in Konsole
%d : %n 
allows for CurrentDir: CurrentRunnignProgram

**Comment by pmattern** [comment]
+1

After having a closer look at Konsole, Xfce4 Terminal Emulator and xterm I'd suggest to go with the latter, which has been proposed recently in #111 as well.
Xfce4 Terminal basically behaves the same as xterm but has some albeit minor flaws regarding su. Konsole seems to feature several kinds of display none of which seems really helpful to me:
First there's '\<directory\> : \<process\>' which gets shown permanently in tabs except during SSH sessions and in windows' title bars by default. 'directory' is stating only the last one of the current path, e. g. "postfix" if either in /etc/postfix or /var/spool/postfix. Regarding su sessions ('su \<user\>') it sticks with the one su had been invoked in but doesn't display the one the current user is actually in. Also, no information about the current user is provided in su sessions.
During SSH sessions tabs' display turns into a permanent '(\<remote user\>) \<host\>' which doesn't provide information about the current path on the remote system either.
The last one is '\<user\>@\<hostname\>:\<path\>'. This gets displayed in windows' title bars if "Show window title on the title bar" is set and is basically the same as in xterm. But unlike xterm Konsole doesn't handle modifications of the window title as e. g. made by vim.

**Comment by ryanreich** [comment]
+1 This is very useful in Gentoo, whose package manager sets the terminal title while merging.  Gentoo merges can be quite long; it's nice to know what package is currently in operation.

**Comment by jleclanche** [comment]
PRs welcome :)

**Comment by ryanreich** [comment]
If I'd ever used qt before, I'd be all over it.  Still considering it :)
ᐧ

**Comment by jleclanche** [comment]
Don't hesitate to ask for mentorship on the lxde-list mailing list or the #lxde channel on Freenode.

**Comment by palinek** [comment]
> and the window title as well... I just have to find how to do it

You just need to sniff for the [particular escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code). 

ESC ] -> Starts a control string for the operating system to use. OSC sequences are similar to CSI sequences, but are not limited to integer arguments. In general, these control sequences are terminated by ST.[13]:8.3.89 In xterm, they may also be terminated by BEL.[14] For example, in xterm, the window title can be set by `OSC 0;this is the window title BEL.`

In bash this is achieved by setting the `PROMPT_COMMAND` variable (executed after each interactive command), e.g.: `PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/~}\007"'`

**Comment by yan12125** [comment]
I followed the idea of @palinek and implemented a simple version at #251. Please have a look, thanks!

**Comment by palinek** [comment]
Implemented in #252
